### PR TITLE
Work with readonly src dirs

### LINKED ISSUE #38: Not working on read-only src trees
This is not working when building out of tree with a read-only src directory. See
https://github.com/tpm2-software/tpm2-tss/issues/2271

So we are considering git.mk to not be part of `all:` if git.mk could just skip generation if it fails.

### PR DESCRIPTION
**Pull request by behdad**
Fixes https://github.com/behdad/git.mk/issues/38

### CODE REVIEW

**Comment by AndreasFuchsSIT** [comment]
Works for me.
What does @geoffthorpe say ?

**Comment by AndreasFuchsSIT** [comment]
Maybe `echo "WARNING: Cannot create $@ file; skipping"` is even better.

**Comment by behdad** [comment]
Right.

**Comment by behdad** [comment]
Adjusted.

**Pull request merged**
